# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fechasuscripcion_cliente',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero_cliente',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numdoc_cliente',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipodoc_cliente',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10),
        ),
    ]
