# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_auto_20170402_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechasuscripcion_cliente',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numdoc_cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
